---
title: "primertrabajor"
author: "diego"
format: html
editor: visual
bibliography: tesisriesgopolitico.bib
link-citations: true
---

# Riesgo politico en Chile y su impacto en las inversiones extranjeras.

Por: Diego Martínez

## Introducción:

Los trabajos sobre riesgo politico son propios de los profesionales de negocios internacionales [ver @jeffreysimonTheoreticalPerspectivePolitical1984], sin embargo es posible encontrar trabajos que aborden el riesgo politico desde la ciencia política este es el caso del estudio de Johannes Leitner [ver @johannesleitner2016] que define como el riesgo político como un concepto que cubre aquellos factores de riesgo para las empresas internacionales que están arraigados en el entorno político e institucional de un país pero que tienen consecuencias inmediatas en el desempeño de la empresa. En este trabajo aborda el nuevo panorama politico en el que se encuentran insertas las empresas, asi como la importancia del Estado y como su marco institucional influye en la toma de decisiones de empresas he inversionistas extranjeros.

Para demostrar la importancia de los marcos intitucionales y las decisiones politicas se expondra el caso de las politicas macroprudenciales de la UE [ver @eliasbengtssonMacroprudentialPolicyEU2020] asi mismo haran estudios comparativos sobre el mercado de la energia \[ver\@tamarajoysomers-cox2014\] que servira de conector para ver como paises latinoamericanos pueden sacar provecho de sus ventajas comparativas con minerales como el litio o el cobre para la transición energética global.

Finalmente todo esto se hará con el motivo de comprender el riesgo politico en Chile y tratar de ver posibles caminos de solucion para los riesgos que amenazan a la nación: Como lo son la corrupción, crimen organizado y el clima de negocios (esto segun el ultimo informe de riesgo politico en America Latina) todos factores que imposibilitan el desarrollo economico y las ventajas comparativas que podria tener Chile en la transición energética mundial. Se espera que ante un marco regulatorio bien definido y que en paises donde la corrupcion sea menor el riesgo politico en consecuencia tambien lo sea.
